- name: check if ZSH is the default shell
  lineinfile: line="Set shell to /opt/local/bin/zsh for user {{ USERNAME }}" dest="{{ INSTALLATION_TARGET }}/ansible.txt" state=present create=yes group={{ USERGROUP }} owner={{ USERNAME }} mode=0600
  register: shell_configured
  when: PACKAGE_MANAGER == 'macports'
- name: set ZSH as the default shell
  command: su - root -c "chsh -s /opt/local/bin/zsh {{ USERNAME }}"
  when: PACKAGE_MANAGER == 'macports' and shell_configured|changed
- name: set ZSH as the default shell
  user: name={{ user }} shell=/usr/bin/zsh
  when: PACKAGE_MANAGER == 'yum'
