# linux
- name: set ZSH as the default shell
  user: name={{ user }} shell=/usr/bin/zsh
  when: host_package_manager != 'macports'
# mac
- name: check if ZSH is the default shell
  lineinfile: line="Set shell to /opt/local/bin/zsh for user {{ user }}" dest="{{ mac_installation_target }}/ansible.txt" state=present create=yes group={{ group }} owner={{ user }} mode=0600
  register: shell_configured
  when: host_package_manager == 'macports'
- name: set ZSH as the default shell
  command: su - root -c "chsh -s /opt/local/bin/zsh {{ user }}"
  when: host_package_manager == 'macports' and shell_configured|changed
