---
- name: create database user
  postgresql_user: name={{ db_user }}
  sudo: yes
  sudo_user: postgres
- name: create database
  postgresql_db: name={{ db_name }} owner={{ db_user }}
  sudo: yes
  sudo_user: postgres
  when: db_name != 'all'
- name: configure database peer access
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf regexp="^ *local *{{ db_name }}" line="  local   {{ db_name }}   {{ db_user }}   peer"
  when: db_peer_map.name is not defined
  notify:
    - restart postgresql
- name: configure database peer access with custom map
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf regexp="^ *local *{{ db_name }}" line="  local   {{ db_name }}   {{ db_user }}   peer   map={{ db_peer_map.name }}"
  when: db_peer_map.name is defined
  notify:
    - restart postgresql
- name: configure peer map
  lineinfile: dest=/var/lib/pgsql/data/pg_ident.conf regexp="^ *{{ db_peer_map.name }} *{{ item.key }} *{{ item.value }}" line="  {{ db_peer_map.name }}   {{ item.key }}   {{ item.value }}"
  when: db_peer_map.mappings is defined
  with_dict: db_peer_map.mappings
  notify:
    - restart postgresql
- name: check if schema is already loaded
  command: psql -U postgres -c '\d' {{ db_name }}
  sudo: yes
  sudo_user: postgres
  register: db_schema_loaded
  changed_when: "'No relations found' in db_schema_loaded.stdout"
  when: db_schema_file is defined
  notify:
    - load schema
