---
- name: apt-get install postfix
  apt: pkg=postfix state=latest
  when: PACKAGE_MANAGER == "apt"
  notify:
    - restart postfix
  tags:
    - postfix
- name: yum install postfix
  yum: pkg=postfix state=latest
  when: PACKAGE_MANAGER == "yum"
  notify:
    - restart postfix
  tags:
    - postfix
- name: start postfix
  action: service name=postfix enabled=yes state=started
  tags:
    - postfix
- name: configure postfix domain
  lineinfile: dest=/etc/postfix/main.cf regexp='^mydomain ?=' insertafter=^#mydomain line="mydomain = ${POSTFIX_DOMAIN}"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix hostname
  lineinfile: dest=/etc/postfix/main.cf regexp='^myhostname ?=' insertafter=^#myhostname line="myhostname = ${POSTFIX_HOSTNAME}"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix relayhost
  lineinfile: dest=/etc/postfix/main.cf regexp='^relayhost ?=' insertafter=^#relayhost line="relayhost = ${POSTFIX_RELAYHOST}"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix smtp_use_tls
  lineinfile: dest=/etc/postfix/main.cf regexp='^smtp_use_tls ?=' line="smtp_use_tls = yes"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix smtp_sasl_auth_enable
  lineinfile: dest=/etc/postfix/main.cf regexp='^smtp_sasl_auth_enable ?=' line="smtp_sasl_auth_enable = yes"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix smtp_sasl_password_maps
  lineinfile: dest=/etc/postfix/main.cf regexp='^smtp_sasl_password_maps ?=' line="smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix smtp_tls_CAfile
  lineinfile: dest=/etc/postfix/main.cf regexp='^smtp_tls_CAfile ?=' line="smtp_tls_CAfile = ${POSTFIX_CERTS}"
  notify:
    - restart postfix
  tags:
    - postfix
- name: configure postfix smtp_sasl_security_options
  lineinfile: dest=/etc/postfix/main.cf regexp='^smtp_sasl_security_options ?=' line="smtp_sasl_security_options ="
  notify:
    - restart postfix
  tags:
    - postfix
- name: template /etc/postfix/sasl_passwd
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl_passwd group=root owner=root mode=0600
  notify:
    - restart postfix
  tags:
    - postfix
- name: postmap /etc/postfix/sasl_passwd
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd creates=/etc/postfix/sasl_passwd.db
  notify:
    - restart postfix
  tags:
    - postfix
