---
- name: configure selinux to allow nginx access to configuration files in /web
  script: roles/nginx-server/scripts/selinux.chcon.sh {{ item }} httpd_config_t
  with_items:
    - /web/conf.d
  register: selinux_context_changed
  changed_when: "selinux_context_changed.rc != 0"
