---
- name: Install vim-epidemic gem
  command: su - {{ USERNAME }} -c "cd && source .rvm/scripts/rvm && gem install --no-rdoc --no-ri vim-epidemic" creates="{{ USERHOME }}/.rvm/gems/ruby-{{ RUBY_VERSION }}/bin/vim-epidemic"
- name: Run vim-epidemic
  command: su - {{ USERNAME }} -c "cd && export VIM_RUBY=/opt/local/bin/ruby1.9 && source .rvm/scripts/rvm && vim-epidemic update" creates={{ USERHOME }}/.vim/bundle/Command-T
