- name: Install pathogen
  command: su - {{ user }} -c "mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim" creates="{{ host_user_homes | default('/home') }}/{{ user }}/.vim/autoload/pathogen.vim"
