---
- name: rvm install {{ version }} for {{ user }}
  command: su - {{ user }} -c "cd && rvm install {{ version }}" creates=/home/{{ user }}/.rvm/rubies/ruby-{{ version }}
  when: OS_FAMILY != 'darwin'
  tags: rvm
- name: rvm install {{ version }} for {{ user }}
  command: su - {{ user }} -c "cd && source .rvm/scripts/rvm && rvm install {{ version }}" creates=/Users/{{ user }}/.rvm/rubies/ruby-{{ version }}
  when: OS_FAMILY == 'darwin'
  tags: rvm
