- name: install GnuPG v1 (yum)
  yum: pkg=gnupg state=latest
  when: host_package_manager == 'yum'
- name: install GnuPG v1 (MacPorts)
  macports: name=gnupg state=installed
  when: host_package_manager == 'macports'
