- name: yum install gnupg
  yum: pkg=gnupg state=latest
  when: host_package_manager == 'yum'
- name: port install gnupg
  macports: name=gnupg state=installed
  when: host_package_manager == 'macports'
