---
- name: install rvm
  command: su - {{ user }} -c 'cd && curl -sSL https://get.rvm.io | bash -s stable' creates={{ host_user_homes | default("/home") }}/{{ user }}/.rvm
- name: rvm requirements
  command: /home/{{ user }}/.rvm/bin/rvm requirements
  register: command_result
  changed_when: "'Installing' in command_result.stdout"
- name: rvm install {{ ruby_version }}
  command: su - {{ user }} -c 'cd && rvm install {{ ruby_version }}' creates={{ host_user_homes | default("/home") }}/{{ user }}/.rvm/rubies/{{ ruby_version }}
  when: ruby_version is defined
- name: rvm use --default {{ ruby_version }}
  command: su - {{ user }} -c "rvm list|grep -v '#'|grep '*'|cut -d ' ' -f 2|grep {{ ruby_version }} &>/dev/null && echo {{ ruby_version }} is already the default || rvm use --default {{ ruby_version }}"
  register: command_result
  changed_when: "'already the default' not in command_result.stdout"
  when: ruby_version is defined and ruby_version_default
