- name: yum install zsh
  yum: pkg=zsh state=latest
  when: PACKAGE_MANAGER == 'yum'
- name: apt-get install zsh
  apt: name=zsh state=latest
  when: PACKAGE_MANAGER == 'apt'
- name: port install zsh
  macports: name=zsh state=installed
  when: PACKAGE_MANAGER == 'macports'
