# yum
- name: install base tools (yum)
  yum: pkg={{ item }} state=latest
  with_items:
    - curl
    - gcc
    - gcc-c++
    - make
    - python-setuptools
    - rsync
    - wget
  when: host_package_manager == 'yum'
# aptitude
- name: install base tools (aptitude)
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - curl
    - python-setuptools
    - rsync
    - wget
  when: host_package_manager == 'apt'
# MacPorts
- name: install base tools (MacPorts)
  macports: name={{ item }} state=installed
  with_items:
    - curl
    - rsync
    - wget
  when: host_package_manager == 'macports'
