---
- name: useradd {{ user }}
  user: name={{ user }}
- name: mkdir /web/sites/{{ user }}
  file: path=/web/sites/{{ user }} group={{ host_name }}-web owner={{ user }} mode=0750 state=directory
- name: symlink /home/{{ user }}/web
  file: path={{ host_user_homes | default("/home") }}/{{ user }}/web src=/web/sites/{{ user }} state=link
- name: mkdir /run/web/{{ user }}
  file: path=/run/web/{{ user }} group={{ host_name }}-web owner={{ user }} mode=0750 setype=httpd_var_run_t state=directory
