---
- yum: pkg=nodejs state=latest
  when: PACKAGE_MANAGER == "yum"
- yum: pkg=npm state=latest
  when: PACKAGE_MANAGER == "yum"
- macports: name=nodejs state=installed
  when: PACKAGE_MANAGER == "macports"
- macports: name=npm state=installed
  when: PACKAGE_MANAGER == "macports"
