- name: Check if $app_name is installed
  shell: test -d "/Applications/{{ app_name }}.app" && echo installed || echo absent
  register: installed
  changed_when: installed.stdout.find('installed') == -1
- include: install-new-app.yml 
  when: installed|changed
