- name: Check if archive is installed
  lineinfile: line="Copied {{ archive }} to {{ DOWNLOADS }}" dest="{{ INSTALLATION_TARGET }}/ansible.txt" state=present create=yes group={{ USERGROUP }} owner={{ USERNAME }} mode=0600
  register: installed
- name: Copy archive
  copy: src="{{ INSTALLATION_SOURCE }}/{{ archive }}" dest="{{ DOWNLOADS }}/{{ archive }}" group={{ USERGROUP }} owner={{ USERNAME }}
  when: installed|changed
- name: Link archive
  file: path="{{ USERHOME }}/Desktop/{{ archive }}" src="{{ DOWNLOADS }}/{{ archive }}" state=link
  when: installed|changed
