---
- name: Create downloads directory
  file: path={{ DOWNLOADS }} group={{ USERGROUP }} owner={{ USERNAME }} state=directory
# Applications to install
- include: install-app.yml app_name="Adium" app_version="1.5.10" archive_type=dmg
- include: install-app.yml app_name="Colloquy" app_version="2.4.3" archive_type=zip
- include: install-app.yml app_name="Cyberduck" app_version="4.4.5" archive_type=zip
- include: install-app.yml app_name="Firefox" app_version="30.0" archive_type=dmg
- include: install-app.yml app_name="GIMP" app_version="2.8.10" archive_type=dmg
- include: install-app.yml app_name="Google Chrome" app_version="35.0" archive_type=dmg
- include: install-app.yml app_name="HandBrake" app_version="0.9.9" archive_type=dmg
- include: install-app.yml app_name="KeePassX" app_version="0.4.3" archive_type=dmg
- include: install-app.yml app_name="LibreOffice" app_version="4.2.4" archive_type=dmg
- include: install-app.yml app_name="Quicksilver" app_version="1.1.3" archive_type=dmg
- include: install-app.yml app_name="Skype" app_version="6.15" archive_type=dmg
- include: install-app.yml app_name="smcFanControl" app_version="2.4" archive_type=zip
- include: install-app.yml app_name="Stuffit Expander" app_version="15.0.7" archive_type=dmg
- include: install-app.yml app_name="Synology Assistant" app_version="5.0-4448" archive_type=dmg
- include: install-app.yml app_name="TextMate" app_version="2.0-alpha" archive_type=tbz
- include: install-app.yml app_name="Transmission" app_version="2.83" archive_type=dmg
- include: install-app.yml app_name="VLC" app_version="2.1.4" archive_type=dmg
# Applications to be installed manually
- include: link-archive.yml archive="GrowlNotify 2.1.zip"
- include: link-archive.yml archive="MacTeX 2013.pkg"
- include: link-archive.yml archive="Steam.dmg"
- include: link-archive.yml archive="USB-Overdrive 302.dmg"
- include: link-archive.yml archive="VirtualBox 4.3.12.dmg"
- include: link-archive.yml archive="VMware Fusion 6.0.3.dmg"
# Configuration to be applied manually
- include: link-archive.yml archive="Fonts.zip"
- include: link-archive.yml archive="Terminal.zip"
