---
- name: Create downloads directory
  file: path={{ DOWNLOADS }} group={{ USERGROUP }} owner={{ USERNAME }} state=directory
- name: Create transient directory
  file: path="{{ USERHOME }}/Transient" group={{ USERGROUP }} owner={{ USERNAME }} state=directory
# Applications to install
- include: install-app.yml app_name="Adium" app_version="1.5.10" archive_type=dmg
- include: install-app.yml app_name="Colloquy" app_version="2.4.3" archive_type=zip
- include: install-app.yml app_name="Cyberduck" app_version="4.7" archive_type=zip
- include: install-app.yml app_name="Firefox" app_version="38.0.5" archive_type=dmg
- include: install-app.yml app_name="GIMP" app_version="2.8.10" archive_type=dmg
- include: install-app.yml app_name="Google Chrome" app_version="43.0" archive_type=dmg
- include: install-app.yml app_name="HandBrake" app_version="0.10.2" archive_type=dmg
- include: install-app.yml app_name="KeePassX" app_version="0.4.3" archive_type=dmg
- include: install-app.yml app_name="LibreOffice" app_version="4.4.3" archive_type=dmg
- include: install-app.yml app_name="Skype" app_version="7.8" archive_type=dmg
- include: install-app.yml app_name="smcFanControl" app_version="2.5.2" archive_type=zip
- include: install-app.yml app_name="Stuffit Expander" app_version="15.0.7" archive_type=dmg
- include: install-app.yml app_name="Synology Assistant" app_version="5.2-5566" archive_type=dmg
- include: install-app.yml app_name="TextMate" app_version="2.0-beta" archive_type=tbz
- include: install-app.yml app_name="Transmission" app_version="2.84" archive_type=dmg
- include: install-app.yml app_name="VLC" app_version="2.2.1" archive_type=dmg
# Applications to be installed manually
- include: link-archive.yml archive="Boot2Docker 1.6.2.pkg"
- include: link-archive.yml archive="GrowlNotify 2.1.zip"
- include: link-archive.yml archive="MacTeX 2015.pkg"
- include: link-archive.yml archive="Steam.dmg"
- include: link-archive.yml archive="USB-Overdrive 3.1.dmg"
- include: link-archive.yml archive="Vagrant 1.7.2.dmg"
- include: link-archive.yml archive="VirtualBox 4.3.28.dmg"
- include: link-archive.yml archive="VMware Fusion 7.1.1.dmg"
# Configuration to be applied manually
- include: link-archive.yml archive="Fonts.zip"
- include: link-archive.yml archive="Terminal.zip"
