---
- name: groupadd {{ HOSTNAME }}-web
  group: name={{ HOSTNAME }}-web state=present
- name: add users to {{ HOSTNAME }}-web group
  action: user name={{ item }} append=yes groups={{ HOSTNAME }}-web
  with_items: web_users
  # FIXME: this should restart nginx
- name: mkdir /web
  file: path=/web group={{ HOSTNAME }}-web mode=0751 state=directory
- name: mkdir /web/certificates
  file: path=/web/certificates group=root owner=root mode=0700 setype=httpd_config_t state=directory
- name: mkdir /web/sites
  file: path=/web/sites group={{ HOSTNAME }}-web mode=0751 setype=httpd_sys_content_t state=directory
- name: mkdir /run/web
  file: path=/run/web group={{ HOSTNAME }}-web owner=root mode=0751 setype=httpd_var_run_t state=directory
- name: ln -s /run/web /web/run
  file: src=/run/web dest=/web/run group={{ HOSTNAME }}-web owner=root state=link
