---
- name: yum install git-all
  yum: pkg=git-all state=latest
  when: host_package_manager == 'yum'
- name: apt-get install git-all
  apt: pkg=git-all state=latest
  when: host_package_manager == 'apt'
- name: Install Git
  macports: name=git state=installed
  when: host_package_manager == 'macports'
- name: Install Git extras
  macports: name=git-extras state=installed
  when: host_package_manager == 'macports'
- name: Install hub
  macports: name=hub state=installed
  when: host_package_manager == 'macports'
