# httpie
- name: install base tools (yum)
  yum: pkg={{ item }} state=latest
  with_items:
    - httpie
    #- hub (hub seems to be bugged on fedora)
  when: host_package_manager == 'yum'
- name: install base tools (MacPorts)
  macports: name={{ item }} state=installed
  with_items:
    - httpie
    - hub # TODO: mode hub to github role
    - jq
  when: host_package_manager == 'macports'
# ack
- name: mkdir /opt/bin
  file: path=/opt/bin state=directory # TODO: add to root $PATH
- name: install ack
  get_url: url=http://beyondgrep.com/ack-2.14-single-file dest=/opt/bin/ack mode=0755 sha256sum=1d203cfbc52ce8f49e3992be1cd3e4d7d5dfb7daa3739e8628aa9858ccc5b9df
# direnv
- name: clone direnv
  git: repo=https://github.com/zimbatm/direnv.git dest=/opt/direnv
  notify:
    - install direnv
  when: host_package_manager != 'macports'
- name: clone direnv (macports)
  git: repo=https://github.com/zimbatm/direnv.git dest=/opt/direnv executable=/opt/local/bin/git
  notify:
    - install direnv
  when: host_package_manager == 'macports'
# TODO: add jarg
