---
- yum: pkg=nodejs state=latest
  when: PACKAGE_MANAGER == "yum"
- yum: pkg=npm state=latest
  when: PACKAGE_MANAGER == "yum"
- name: Install NodeJS
  macports: name=nodejs state=installed
  when: PACKAGE_MANAGER == "macports"
- name: Install NPM
  macports: name=npm state=installed
  when: PACKAGE_MANAGER == "macports"
