---
- name: Install NodeJS
  yum: pkg=nodejs state=latest
  when: host_package_manager == "yum"
- name: Install NPM
  yum: pkg=npm state=latest
  when: host_package_manager == "yum"
- name: Install NodeJS
  macports: name=nodejs state=installed
  when: host_package_manager == "macports"
- name: Install NPM
  macports: name=npm state=installed
  when: host_package_manager == "macports"
