- name: Make installation tracking directory
  file: path="{{ host_user_homes | default('/home') }}/{{ user }}/Installation" group={{ group | default(user) }} owner={{ user }} mode=0700 state=directory
