---
- name: apt-get install logwatch with fortune mods
  apt: pkg=${item} state=latest
  with_items:
    - logwatch
    - fortunes
    - fortune-mod
    - fortunes-bofh-excuses
    - fortunes-mario
    - fortunes-min
    - fortunes-off
    - fortunes-spam
  tags:
    - logwatch
