---
- name: apt-get update
  apt: update-cache=yes
  when: PACKAGE_MANAGER == 'apt'
- include: system.yml
- include: tools-{{ PACKAGE_MANAGER }}.yml
- include: ssh.yml
- include: logwatch-{{ OS_FAMILY }}.yml
