---
- name: apt-get install tools
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - build-essential
    - curl
    - python-setuptools
    - rsync
    - vim
    - wget
    - zsh
  tags:
    - tools
