---
- name: mkdir {{ site_path }}
  file: path={{ site_path }} owner={{ user }} group={{ group | default(user) }} mode=0755 state=directory
- name: configure nginx to serve static site
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ site_identifier }}.conf group=root owner=root
  notify:
    - restart nginx
