- name: Link environment directory
  file: path="{{ USERHOME }}/.env.d" src="{{ USERHOME }}/Safebox/Config/.env.d" state=link
- name: Link Archives directory
  file: path="{{ USERHOME }}/Archives" src="{{ USERHOME }}/Safebox/Archives" state=link
- name: Link Desktop to Dropbox
  file: path="{{ USERHOME }}/Dropbox/Desktop/{{ HUMAN_NAME }}" src="{{ USERHOME }}/Desktop" state=link
- name: Check whether Music directory is linked
  shell: test -L "{{ USERHOME }}/Music" && echo 'yes' || echo 'no'
  register: music_link
  changed_when: music_link.stdout.find('yes') == -1
- name: Archive Music directory
  command: mv "{{ USERHOME }}/Music" "{{ INSTALLATION_TARGET }}/Original Music" creates="{{ INSTALLATION_TARGET }}/Original Music"
  when: music_link|changed
- name: Link Music directory
  file: path="{{ USERHOME }}/Music" src="{{ USERHOME }}/Dropbox/Music" state=link
- name: Check whether Pictures directory is linked
  shell: test -L "{{ USERHOME }}/Pictures" && echo 'yes' || echo 'no'
  register: pictures_link
  changed_when: pictures_link.stdout.find('yes') == -1
- name: Archive Pictures directory
  command: mv "{{ USERHOME }}/Pictures" "{{ INSTALLATION_TARGET }}/Original Pictures" creates="{{ INSTALLATION_TARGET }}/Original Pictures"
  when: pictures_link|changed
- name: Link Pictures directory
  file: path="{{ USERHOME }}/Pictures" src="{{ USERHOME }}/Dropbox/Pictures" state=link
- name: Link Adium 2.0 application support directory
  file: path="{{ USERHOME }}/Library/Application Support/Adium 2.0" src="{{ USERHOME }}/Dropbox/Shared/Library/Application Support/Adium 2.0" state=link
- name: Make Applications directory
  file: path="{{ USERHOME }}/Applications" group={{ USERGROUP }} owner={{ USERNAME }} state=directory
- name: Link IM application
  file: path="{{ USERHOME }}/Applications/IM.app" src="{{ USERHOME }}/Safebox/Automator/IM.app" state=link
