- name: Check whether environment directory already exists
  shell: test -L "{{ USERHOME }}/.env.d" && echo 'yes' || echo 'no'
  register: environment_directory_link
  changed_when: environment_directory_link.stdout.find('yes') == -1
- name: Link environment directory
  command: su - {{ USERNAME }} -c "cd && ln -s {{ USERHOME }}/Safebox/Config/.env.d {{ USERHOME }}/.env.d"
  when: environment_directory_link|changed
- name: Check whether Archives directory already exists
  shell: test -L "{{ USERHOME }}/Archives" && echo 'yes' || echo 'no'
  register: archives_directory_link
  changed_when: archives_directory_link.stdout.find('yes') == -1
- name: Link Archives directory
  command: su - {{ USERNAME }} -c "cd && ln -s {{ USERHOME }}/Safebox/Archives {{ USERHOME }}/Archives"
  when: archives_directory_link|changed
- name: Link Desktop to Dropbox
  file: path="{{ USERHOME }}/Dropbox/Desktop/{{ host_human_name }}" src="{{ USERHOME }}/Desktop" state=link
- name: Check whether Music directory is linked
  shell: test -L "{{ USERHOME }}/Music" && echo 'yes' || echo 'no'
  register: music_link
  changed_when: music_link.stdout.find('yes') == -1
- name: Archive Music directory
  command: mv "{{ USERHOME }}/Music" "{{ INSTALLATION_TARGET }}/Original Music" creates="{{ INSTALLATION_TARGET }}/Original Music"
  when: music_link|changed
- name: Link Music directory
  file: path="{{ USERHOME }}/Music" src="{{ USERHOME }}/Dropbox/Music" state=link
- name: Check whether Pictures directory is linked
  shell: test -L "{{ USERHOME }}/Pictures" && echo 'yes' || echo 'no'
  register: pictures_link
  changed_when: pictures_link.stdout.find('yes') == -1
- name: Archive Pictures directory
  command: mv "{{ USERHOME }}/Pictures" "{{ INSTALLATION_TARGET }}/Original Pictures" creates="{{ INSTALLATION_TARGET }}/Original Pictures"
  when: pictures_link|changed
- name: Link Pictures directory
  file: path="{{ USERHOME }}/Pictures" src="{{ USERHOME }}/Dropbox/Pictures" state=link
- name: Link Adium 2.0 application support directory
  file: path="{{ USERHOME }}/Library/Application Support/Adium 2.0" src="{{ USERHOME }}/Dropbox/Shared/Library/Application Support/Adium 2.0" state=link
- name: Make Applications directory
  file: path="{{ USERHOME }}/Applications" group={{ USERGROUP }} owner={{ USERNAME }} state=directory
- name: Check whether IM application already exists
  shell: test -e "{{ USERHOME }}/Applications/IM.app" && echo 'yes' || echo 'no'
  register: im_app_link
  changed_when: im_app_link.stdout.find('yes') == -1
- name: Link IM application
  command: su - {{ USERNAME }} -c "cd && cp -R {{ USERHOME }}/Safebox/Automator/IM.app {{ USERHOME }}/Applications"
  when: im_app_link|changed
