- name: install dev tools
  macports: name={{ item }} state=installed
  with_items:
    - ansible
    - libxml2 # required for nokogiri
    - libxslt # required for nokogiri
    - py27-pip
    - ruby19
    - ruby20
    - ruby21
    - sqlite3
- name: port select pip pip27
  script: common/port-select.sh pip pip27
  register: selected
  changed_when: selected.stdout.find('already active') == -1
- name: port select ruby ruby21
  script: common/port-select.sh ruby ruby21
  register: selected
  changed_when: selected.stdout.find('already active') == -1
- name: port select python python27
  script: common/port-select.sh python python27
  register: selected
  changed_when: selected.stdout.find('already active') == -1
- name: install dev gems
  command: su - {{ USERNAME }} -c "cd && source .rvm/scripts/rvm && gem install --no-rdoc --no-ri {{ item.name }}" creates="{{ USERHOME }}/.rvm/gems/ruby-{{ rvm_ruby_version }}/bin/{{ item.bin }}"
  with_items:
    - { name: 'dotenv', bin: 'dotenv' }
    - { name: 'git_go', bin: 'gg' }
    - { name: 'scide', bin: 'scide' }
