---
- name: postgresql
  yum: pkg=postgresql state=latest
- name: postgresql-devel
  yum: pkg=postgresql-devel state=latest
- name: postgresql-server
  yum: pkg=postgresql-server state=latest
- name: postgresql-contrib
  yum: pkg=postgresql-contrib state=latest
- name: set up /var/lib/pgsql/data
  file: path=/var/lib/pgsql/data group=postgres owner=postgres mode=0700 state=directory
- name: init postgresql database
  command: /bin/su - postgres -c 'initdb -D /var/lib/pgsql/data -E UTF8 --locale=en_US.UTF8' creates=/var/lib/pgsql/data/pg_hba.conf
- name: start postgresql
  service: name=postgresql enabled=yes state=started
