---
- name: mkdir /var/lib/pgsql/data/ansible/pg_hba
  file: path=/var/lib/pgsql/data/ansible/pg_hba group=postgres owner=postgres mode=0700 state=directory
- name: mkdir /var/lib/pgsql/data/ansible/pg_ident
  file: path=/var/lib/pgsql/data/ansible/pg_ident group=postgres owner=postgres mode=0700 state=directory
- name: template pg_hba system
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/ansible/pg_hba/0system group=postgres owner=postgres mode=0700
- name: template pg_ident system
  template: src=pg_ident.conf.j2 dest=/var/lib/pgsql/data/ansible/pg_ident/0system group=postgres owner=postgres mode=0700
