---
- name: generate wrapper
  command: su - {{ user }} -c 'cd && rvm wrapper {{ ruby_version }} {{ prefix | default(user) }} {{ binary }}' creates={{ host_user_homes | default("/home") }}/{{ user }}/.rvm/bin/{{ prefix | default(user) }}_{{ binary }}
