- name: Install EncFS
  macports: name=encfs state=installed
- name: Ensure boxafe name is in environment file
  lineinfile: line="BOXAFE_NAME=\"{{ boxafe_name }}\"" dest="{{ user_home }}/.env" state=present create=yes group={{ group }} owner={{ user }} mode=0600
- name: Ensure boxafe root is in environment file
  lineinfile: line="BOXAFE_ROOT=\"{{ boxafe_root }}\"" dest="{{ user_home }}/.env" state=present create=yes group={{ group }} owner={{ user }} mode=0600
- name: Ensure boxafe EncFS config is in environment file
  lineinfile: line="BOXAFE_ENCFS_CONFIG=\"~/{{ boxafe_encfs_config }}\"" dest="{{ user_home }}/.env" state=present create=yes group={{ group }} owner={{ user }} mode=0600
- name: Ensure boxafe password file is in environment file
  lineinfile: line="BOXAFE_PASSWORD_FILE=\"~/{{ boxafe_password_file }}\"" dest="{{ user_home }}/.env" state=present create=yes group={{ group }} owner={{ user }} mode=0600
- name: Install boxafe gem
  command: su - {{ user }} -c "cd && source .rvm/scripts/rvm && gem install --no-rdoc --no-ri boxafe" creates="{{ user_home }}/.rvm/gems/ruby-{{ rvm_ruby_version }}/bin/boxafe"
- name: Ensure EncFS config file permissions
  file: path="{{ user_home }}/{{ boxafe_encfs_config }}" group={{ group }} owner={{ user }} mode=0400
- name: Ensure safebox password file permissions
  file: path="{{ user_home }}/{{ boxafe_password_file }}" group={{ group }} owner={{ user }} mode=0400
- name: Ensure boxafe configuration
  file: path="{{ user_home }}/.boxafe.rb" src="{{ boxafe_config }}" state=link
- name: Mount boxafe
  command: su - {{ user }} -c "cd && export PATH=/opt/local/bin:$PATH && source .rvm/scripts/rvm && rvm use {{ rvm_ruby_version }} && boxafe mount" creates=/Volumes/{{ boxafe_name }}
- name: Link Safebox
  file: path="{{ user_home }}/Safebox" src="/Volumes/Safebox" state=link
- name: Mount boxafe on startup
  command: su - {{ user }} -c "cd && source .rvm/scripts/rvm && boxafe start" creates="{{ user_home }}/Library/LaunchAgents/com.alphahydrae.boxafe.plist"
