- name: Check if env repository exists
  shell: test -d "{{ USERHOME }}/Projects/env" && echo exists || echo absent
  register: exists
  changed_when: exists.stdout.find('exists') == -1
- name: Make projects directory
  file: path="{{ USERHOME }}/Projects" group={{ USERGROUP }} owner={{ USERNAME }} mode=0700 state=directory
  when: exists|changed
- name: Clone environment repository
  command: su - {{ USERNAME }} -c "cd && cd Projects && git clone git@github.com:{{ GITHUB_NAME }}/env.git"
  when: exists|changed
