- name: Check if env repository exists
  shell: test -d "{{ USERHOME }}/Projects/env"
  register: exists
  changed_when: exists.rc != 0
- name: Make projects directory
  file: path="{{ USERHOME }}/Projects" group=staff owner={{ USERNAME }} mode=0700 state=directory
  when: exists|changed
- name: Clone environment repository
  command: su - {{ USERNAME }} -c "cd && cd Projects && git clone git@github.com:{{ GITHUB_NAME }}/env.git"
  when: exists|changed
