---
- name: mkdir {{ certificate_dir }}/{{ certificate_domain }}
  file: path={{ certificate_dir }}/{{ certificate_domain }} group=root owner=root mode=0700 state=directory
- name: file {{ certificate_dir }}/{{ certificate_domain }}/{{ item }} (manual installation)
  file: path={{ certificate_dir }}/{{ certificate_domain }}/{{ item }} group=root owner=root mode=0400 state=file
  with_items:
    - server.key
    - server.crt
    - server.pem
