- macports: name=redis state=installed
  when: host_package_manager == 'macports'
- script: common/port-load.sh redis
  when: host_package_manager == 'macports'
  register: loaded
  changed_when: loaded.stdout.find('already loaded') == -1
