- macports: name=redis state=installed
  when: PACKAGE_MANAGER == 'macports'
- script: common/port-load.sh redis
  when: PACKAGE_MANAGER == 'macports'
  register: loaded
  changed_when: loaded.stdout.find('already loaded') == -1
